//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService2Test.ConvertMyTemp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConvertMyTemp.IConvertTemperature")]
    public interface IConvertTemperature {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConvertTemperature/CtoF", ReplyAction="http://tempuri.org/IConvertTemperature/CtoFResponse")]
        string CtoF(decimal celcius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConvertTemperature/CtoF", ReplyAction="http://tempuri.org/IConvertTemperature/CtoFResponse")]
        System.Threading.Tasks.Task<string> CtoFAsync(decimal celcius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConvertTemperature/FtoC", ReplyAction="http://tempuri.org/IConvertTemperature/FtoCResponse")]
        string FtoC(decimal fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConvertTemperature/FtoC", ReplyAction="http://tempuri.org/IConvertTemperature/FtoCResponse")]
        System.Threading.Tasks.Task<string> FtoCAsync(decimal fahrenheit);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConvertTemperatureChannel : WcfService2Test.ConvertMyTemp.IConvertTemperature, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConvertTemperatureClient : System.ServiceModel.ClientBase<WcfService2Test.ConvertMyTemp.IConvertTemperature>, WcfService2Test.ConvertMyTemp.IConvertTemperature {
        
        public ConvertTemperatureClient() {
        }
        
        public ConvertTemperatureClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConvertTemperatureClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertTemperatureClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertTemperatureClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CtoF(decimal celcius) {
            return base.Channel.CtoF(celcius);
        }
        
        public System.Threading.Tasks.Task<string> CtoFAsync(decimal celcius) {
            return base.Channel.CtoFAsync(celcius);
        }
        
        public string FtoC(decimal fahrenheit) {
            return base.Channel.FtoC(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<string> FtoCAsync(decimal fahrenheit) {
            return base.Channel.FtoCAsync(fahrenheit);
        }
    }
}
